[package]
name = "betterv"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonwebtoken = "9"
lazy_static = "1"
actix-rt = "2"
log = "0.4"
env_logger = "0.10"